[default]
SQLALCHEMY_DATABASE_URI = 'SQLITE:///teste.db'
TITLE = "vitreus"
EXTESIONS = [
    #"vitreus.ext.admin",
    "vitreus.ext.apperence",
    #"vitreus.ext.auth",
    #"vitreus.ext.commands",
    "vitreus.ext.configuration",
    #"vitreus.ext.database",
    "vitreus.blueprints.webiu",
    #"vitreus.blueprints.restapi"
]


[production]
SQLALCHEMY_DATABASE_URI='postgres:///'

