[default]
SQLALCHEMY_DATABASE_URI = 'sqlite:///teste.db'
SQLALCHEMY_TRACK_MODIFICATIONS = 'True'
TITLE = "vitreus"
EXTENSIONS = ["vitreus.ext.appearance:init_app",
    "vitreus.ext.database:init_app",
    "vitreus.ext.commands:init_app",
    "vitreus.blueprints.webui:init_app",
    
    
    ]


[production]
#SQLALCHEMY_DATABASE_URI='postgres:///'

#"vitreus.blueprints.restapi"#"vitreus.ext.database",#"vitreus.ext.auth",
    #"vitreus.ext.commands",#"vitreus.ext.admin",